### ISSUE TITLE
64 bit support?

### ISSUE THREAD

**Issue by bitfabrikken** [omorandi/TiViewShadow#11]
App Store requires 64 bit support come february 2015 - any plans for this?

**Comment by omorandi** [comment]
I thought this module wasn't actually used anymore, since Ti SDK 3.3.0 introduced shadow properties for views (http://docs.appcelerator.com/titanium/latest/#!/api/Titanium.UI.View-property-viewShadowColor).
However, if you confirm that using the module is a better choice, I'll upgrade for 64bit support

**Comment by bitfabrikken** [comment]
Did not realize that! I'll check it out and report back on this issue if there's any problems.
